# Generated by Django 5.0.6 on 2024-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="convertd_to_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[("low", "LOW"), ("medium", "MEDIUM"), ("high", "HIGH")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
