# Generated by Django 5.0.6 on 2024-05-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_convertd_to_client_alter_lead_priority_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="teams.team",
            ),
            preserve_default=False,
        ),
    ]
