# Generated by Django 5.0.6 on 2024-05-28 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("name",)},
        ),
    ]
