# Generated by Django 5.0.6 on 2024-05-28 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Clients", "0002_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name",)},
        ),
    ]
