# Generated by Django 5.0.6 on 2024-05-30 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Clients", "0005_clientfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientfile",
            old_name="lead",
            new_name="client",
        ),
    ]
